# Generated by Django 3.2 on 2021-04-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='balances',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='item.balance'),
        ),
        migrations.AddField(
            model_name='balance',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
