# Generated by Django 3.2 on 2021-04-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210417_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('lat', models.CharField(max_length=50, null=True)),
                ('lon', models.CharField(max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('store_number', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPaymentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_order_of', models.CharField(max_length=50, null=True)),
                ('payee', models.CharField(max_length=50, null=True)),
                ('payer', models.CharField(max_length=50, null=True)),
                ('payment_method', models.CharField(max_length=50, null=True)),
                ('payment_processor', models.CharField(max_length=50, null=True)),
                ('ppd_id', models.CharField(max_length=50, null=True)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('reference_number', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_owner', models.CharField(max_length=100, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('authorized_date', models.DateField(null=True)),
                ('authorized_date_time', models.DateTimeField(null=True)),
                ('category_id', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('iso_currency_code', models.CharField(max_length=10, null=True)),
                ('merchant_name', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('payment_channel', models.CharField(max_length=20, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('pending_transaction_id', models.BigIntegerField(null=True)),
                ('transaction_code', models.IntegerField(null=True)),
                ('transaction_id', models.CharField(max_length=500, null=True)),
                ('transaction_type', models.CharField(max_length=50, null=True)),
                ('unofficial_currency_code', models.CharField(max_length=10, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='item.account')),
                ('category', models.ManyToManyField(to='item.TransactionCategory')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item.transactionlocation')),
                ('payment_meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item.transactionpaymentmeta')),
            ],
        ),
    ]
