# Generated by Django 3.2 on 2021-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_transactioncategory_transactiondetail_transactionlocation_transactionpaymentmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='transaction_id',
            field=models.CharField(default=0, max_length=500, unique=True),
        ),
    ]
